name: Run Codex CLI

on:
  workflow_dispatch:
    push:
    paths:
      - "inputs/**.txt"

jobs:
  run-codex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Codex CLI
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
        run: npm run run

      - name: Upload Codex output
        uses: actions/upload-artifact@v4
        with:
          name: codex-output
          path: outputs/output.txt
